In [4]:
import numpy as np

review1 = "I LOVE this book about love"
review2 = "No this book was okay"

all_words = [text.lower().split() for text in [review1,review2]]

# flatten this list, can also add lists with + operator
all_words = [word for text in all_words for word in text]
print(f"Flattened all words {all_words}")

unique_words = set(all_words)
print(f"Unique words {unique_words}")

Flattened all words ['i', 'love', 'this', 'book', 'about', 'love', 'no', 'this', 'book', 'was', 'okay']
Unique words {'okay', 'no', 'was', 'about', 'i', 'love', 'this', 'book'}


In [5]:
#make a dictionary of al words

{word: index for index, word in enumerate(unique_words)}

{'okay': 0,
 'no': 1,
 'was': 2,
 'about': 3,
 'i': 4,
 'love': 5,
 'this': 6,
 'book': 7}

In [15]:
# make a dictinoray of all words
vocabulary = {word: index for index, word in enumerate(unique_words)}
print(vocabulary)
def term_frequency_vectorizer(document, vocabulary):
    term_frequency = np.zeros(len(vocabulary))

    for word in document.lower().split():
        index = vocabulary[word]
        term_frequency[index] +=1

    return term_frequency
review1_term_freq = term_frequency_vectorizer(review1, vocabulary)
review2_term_freq = term_frequency_vectorizer(review2, vocabulary)

print(review1_term_freq)
print(review2_term_freq)

{'okay': 0, 'no': 1, 'was': 2, 'about': 3, 'i': 4, 'love': 5, 'this': 6, 'book': 7}
[0. 0. 0. 1. 1. 2. 1. 1.]
[1. 1. 1. 0. 0. 0. 1. 1.]


In [20]:
import pandas as pd

bag_of_words = pd.DataFrame([review1_term_freq, review2_term_freq], columns= vocabulary.keys(), dtype="int16")
bag_of_words

okay  no  was  about  i  love  this  book
0     0   0    0      1  1     2     1     1
1     1   1    1      0  0     0     1     1

## Feature extraction with sklearn

In [30]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer

count_vectorizer = CountVectorizer()
bag_of_words_sparse = count_vectorizer.fit_transform([review1, review2])
bag_of_words_sparse.todense(), count_vectorizer.get_feature_names()

C:\Users\fredr\.virtualenvs\Maskininl-rning-Fredrik-Hegardt-mmrJtyaC\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


(matrix([[1, 1, 2, 0, 0, 1, 0],
         [0, 1, 0, 1, 1, 1, 1]], dtype=int64),
 ['about', 'book', 'love', 'no', 'okay', 'this', 'was'])

In [32]:
bag_of_words = pd.DataFrame(bag_of_words_sparse.todense(),columns= count_vectorizer.get_feature_names())
bag_of_words

C:\Users\fredr\.virtualenvs\Maskininl-rning-Fredrik-Hegardt-mmrJtyaC\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


about  book  love  no  okay  this  was
0      1     1     2   0     0     1    0
1      0     1     0   1     1     1    1

In [33]:
tfidf_transformer = TfidfTransformer()
tfidf = tfidf_transformer.fit_transform(bag_of_words_sparse)
tfidf

<2x7 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [34]:
tfidf.todense()

matrix([[0.4078241 , 0.29017021, 0.81564821, 0.        , 0.        ,
         0.29017021, 0.        ],
        [0.        , 0.35520009, 0.        , 0.49922133, 0.49922133,
         0.35520009, 0.49922133]])

In [36]:
#creates tdidf vector in one go
tfidf_vectorizer = TfidfVectorizer()
tfidf_vectorizer.fit_transform([review1, review2]).todense()

matrix([[0.4078241 , 0.29017021, 0.81564821, 0.        , 0.        ,
         0.29017021, 0.        ],
        [0.        , 0.35520009, 0.        , 0.49922133, 0.49922133,
         0.35520009, 0.49922133]])